export default {
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    { name: 'general', title: 'General' },
    { name: 'seo', title: 'SEO' },
    { name: 'social', title: 'Social & Contact' },
  ],
  fields: [
    {
      name: 'siteName',
      title: 'Site Name',
      type: 'string',
      group: 'general',
    },
    {
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      group: 'general',
    },
    {
      name: 'copyright',
      title: 'Copyright Text',
      type: 'string',
      group: 'general',
    },
    {
      name: 'logo',
      title: 'Logo',
      type: 'image',
      group: 'general',
    },
    {
      name: 'defaultTitle',
      title: 'Default Page Title',
      type: 'string',
      group: 'seo',
    },
    {
      name: 'defaultDescription',
      title: 'Default Meta Description',
      type: 'text',
      group: 'seo',
    },
    {
      name: 'defaultKeywords',
      title: 'Default Keywords',
      type: 'text',
      group: 'seo',
    },
    {
      name: 'instagramMain',
      title: 'Instagram URL (Main)',
      type: 'url',
      group: 'social',
    },
    {
      name: 'instagramKids',
      title: 'Instagram URL (Kids Studio)',
      type: 'url',
      group: 'social',
    },
    {
      name: 'whatsappNumber',
      title: 'WhatsApp Number',
      type: 'string',
      group: 'social',
    },
    {
      name: 'whatsappMessage',
      title: 'WhatsApp Default Message',
      type: 'string',
      group: 'social',
    },
    {
      name: 'phone',
      title: 'Phone Number',
      type: 'string',
      group: 'social',
    },
    {
      name: 'email',
      title: 'Email',
      type: 'string',
      group: 'social',
    },
    {
      name: 'studioAddress',
      title: 'Studio Address',
      type: 'text',
      group: 'social',
    },
    {
      name: 'googleMapsUrl',
      title: 'Google Maps URL',
      type: 'url',
      group: 'social',
    },
    {
      name: 'googleMapsEmbed',
      title: 'Google Maps Embed URL',
      type: 'url',
      group: 'social',
    },
  ],
};
